services:
  python-service:
    env_file:
      - ./services/python/.env.local
    volumes:
      - ./services/python:/app
      - ./protobuf:/proto
      - /app/__pycache__
    command: >
      sh -c "python -m grpc_tools.protoc -I /proto --python_out=/app/proto --grpc_python_out=/app/proto /proto/multimodal.proto && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"

  laravel-api:
    image: mecav-laravel-api:latest
    env_file:
      - ./services/laravel/.env.local
    volumes:
      - ./services/laravel:/var/www/html
      - /var/www/html/vendor
