# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import multimodal_pb2 as multimodal__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in multimodal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultimodalDiagramServiceStub(object):
    """── Service ──────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeText = channel.unary_unary(
                '/multimodal.v1.MultimodalDiagramService/AnalyzeText',
                request_serializer=multimodal__pb2.TextChunk.SerializeToString,
                response_deserializer=multimodal__pb2.DiagramSuggestion.FromString,
                _registered_method=True)
        self.AnalyzeFile = channel.stream_stream(
                '/multimodal.v1.MultimodalDiagramService/AnalyzeFile',
                request_serializer=multimodal__pb2.FileChunk.SerializeToString,
                response_deserializer=multimodal__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.AnalyzeVoice = channel.stream_stream(
                '/multimodal.v1.MultimodalDiagramService/AnalyzeVoice',
                request_serializer=multimodal__pb2.VoiceChunk.SerializeToString,
                response_deserializer=multimodal__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.Process = channel.stream_stream(
                '/multimodal.v1.MultimodalDiagramService/Process',
                request_serializer=multimodal__pb2.MultimodalRequest.SerializeToString,
                response_deserializer=multimodal__pb2.StreamResponse.FromString,
                _registered_method=True)


class MultimodalDiagramServiceServicer(object):
    """── Service ──────────────────────────────────────────────────
    """

    def AnalyzeText(self, request, context):
        """Unary — quick text query → suggestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeFile(self, request_iterator, context):
        """Server-streaming — file upload with streaming AI response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeVoice(self, request_iterator, context):
        """Bidi-streaming — real-time voice transcription + diagram generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request_iterator, context):
        """Generic multimodal (preferred entry-point)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultimodalDiagramServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeText': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeText,
                    request_deserializer=multimodal__pb2.TextChunk.FromString,
                    response_serializer=multimodal__pb2.DiagramSuggestion.SerializeToString,
            ),
            'AnalyzeFile': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeFile,
                    request_deserializer=multimodal__pb2.FileChunk.FromString,
                    response_serializer=multimodal__pb2.StreamResponse.SerializeToString,
            ),
            'AnalyzeVoice': grpc.stream_stream_rpc_method_handler(
                    servicer.AnalyzeVoice,
                    request_deserializer=multimodal__pb2.VoiceChunk.FromString,
                    response_serializer=multimodal__pb2.StreamResponse.SerializeToString,
            ),
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=multimodal__pb2.MultimodalRequest.FromString,
                    response_serializer=multimodal__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multimodal.v1.MultimodalDiagramService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multimodal.v1.MultimodalDiagramService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultimodalDiagramService(object):
    """── Service ──────────────────────────────────────────────────
    """

    @staticmethod
    def AnalyzeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multimodal.v1.MultimodalDiagramService/AnalyzeText',
            multimodal__pb2.TextChunk.SerializeToString,
            multimodal__pb2.DiagramSuggestion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multimodal.v1.MultimodalDiagramService/AnalyzeFile',
            multimodal__pb2.FileChunk.SerializeToString,
            multimodal__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeVoice(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multimodal.v1.MultimodalDiagramService/AnalyzeVoice',
            multimodal__pb2.VoiceChunk.SerializeToString,
            multimodal__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multimodal.v1.MultimodalDiagramService/Process',
            multimodal__pb2.MultimodalRequest.SerializeToString,
            multimodal__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
